services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: